CREATE TABLE IF NOT EXISTS e_certificates (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    reg_id BIGINT NOT NULL,
    nomor_sertif VARCHAR(100) UNIQUE NOT NULL,
    file_url TEXT NOT NULL,
    tgl_terbit TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (reg_id) REFERENCES registrations(id) ON DELETE CASCADE
);
